//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oliviann.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(typeof(Resources));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the root folder from which to start browsing. Only the specified folder and any subfolders that are beneath it will appear in the dialog box..
        /// </summary>
        internal static string ComputerBrowserDialogInvalidOpEx {
            get {
                return ResourceManager.GetString("ComputerBrowserDialogInvalidOpEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it..
        /// </summary>
        internal static string ComputerBrowserDialogThreadStateEx {
            get {
                return ResourceManager.GetString("ComputerBrowserDialogThreadStateEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary collection and/or key cannot be null..
        /// </summary>
        internal static string Dictionary_CollectionOrKey_NotNull {
            get {
                return ResourceManager.GetString("Dictionary_CollectionOrKey_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class generic type must be of type interface..
        /// </summary>
        internal static string ERR_ClassTypeMustBeInterface {
            get {
                return ResourceManager.GetString("ERR_ClassTypeMustBeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error compressing archive &apos;{0}&apos; using format &apos;{1}&apos;.\n{2}.
        /// </summary>
        internal static string ERR_CompressArchive {
            get {
                return ResourceManager.GetString("ERR_CompressArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key has incorrect parameters. Key should be [Section]:[Key]..
        /// </summary>
        internal static string ERR_ConfigIniIncorrectParms {
            get {
                return ResourceManager.GetString("ERR_ConfigIniIncorrectParms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must begin with AppSettings or ConnectionStrings and then the unique key. For example, AppSettings:UserMode or ConnectionStrings:DbName.
        /// </summary>
        internal static string ERR_ConfigKeyPrefix {
            get {
                return ResourceManager.GetString("ERR_ConfigKeyPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key has incorrect parameters. Key should be [KeyName]:[ValueName]..
        /// </summary>
        internal static string ERR_ConfigRegistryIncorrectParms {
            get {
                return ResourceManager.GetString("ERR_ConfigRegistryIncorrectParms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new archive compressor..
        /// </summary>
        internal static string ERR_CreateCompressor {
            get {
                return ResourceManager.GetString("ERR_CreateCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating archive extractor..
        /// </summary>
        internal static string ERR_CreateExtractor {
            get {
                return ResourceManager.GetString("ERR_CreateExtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database {0} can not be compacted because it is currently in use by another application..
        /// </summary>
        internal static string ERR_DB_CanNotCompact {
            get {
                return ResourceManager.GetString("ERR_DB_CanNotCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database {0} already exists and can not be deleted..
        /// </summary>
        internal static string ERR_DB_CanNotDelete {
            get {
                return ResourceManager.GetString("ERR_DB_CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred compacting an {0} database..
        /// </summary>
        internal static string ERR_DB_Compact {
            get {
                return ResourceManager.GetString("ERR_DB_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option of copying an {0} database file is not supported..
        /// </summary>
        internal static string ERR_DB_Copy {
            get {
                return ResourceManager.GetString("ERR_DB_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database provider must be of type {0}..
        /// </summary>
        internal static string ERR_DB_InvalidProvider {
            get {
                return ResourceManager.GetString("ERR_DB_InvalidProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while decompressing archive to the specified directory &apos;{0}&apos;\n{1}.
        /// </summary>
        internal static string ERR_DecompressArchive {
            get {
                return ResourceManager.GetString("ERR_DecompressArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error decompressing file &apos;{0}&apos; from archive to the specified location &apos;{1}&apos;\n{2}.
        /// </summary>
        internal static string ERR_DecompressFile {
            get {
                return ResourceManager.GetString("ERR_DecompressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred deserializing {0}. See inner exception for more details..
        /// </summary>
        internal static string ERR_DeserializingInnerEx {
            get {
                return ResourceManager.GetString("ERR_DeserializingInnerEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index was outside the bounds of the dictionary..
        /// </summary>
        internal static string ERR_DictIndexOutBounds {
            get {
                return ResourceManager.GetString("ERR_DictIndexOutBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; directory could not be found..
        /// </summary>
        internal static string ERR_DirectoryNotFound {
            get {
                return ResourceManager.GetString("ERR_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist and could not be created.\n{1}.
        /// </summary>
        internal static string ERR_DirNotExistCreated {
            get {
                return ResourceManager.GetString("ERR_DirNotExistCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred executing {0}..
        /// </summary>
        internal static string ERR_ExceptionExecuting {
            get {
                return ResourceManager.GetString("ERR_ExceptionExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to adjust process token privileges..
        /// </summary>
        internal static string ERR_FailedAdjustPriv {
            get {
                return ResourceManager.GetString("ERR_FailedAdjustPriv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open process token handle..
        /// </summary>
        internal static string ERR_FailedOpenHandle {
            get {
                return ResourceManager.GetString("ERR_FailedOpenHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open lookup shutdown privilege..
        /// </summary>
        internal static string ERR_FailedOpenShutdownPriv {
            get {
                return ResourceManager.GetString("ERR_FailedOpenShutdownPriv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reboot system..
        /// </summary>
        internal static string ERR_FailedReboot {
            get {
                return ResourceManager.GetString("ERR_FailedReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} file could not be found..
        /// </summary>
        internal static string ERR_FileNotFound {
            get {
                return ResourceManager.GetString("ERR_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms authentication delegate cannot be null..
        /// </summary>
        internal static string ERR_FormsAuthNull {
            get {
                return ResourceManager.GetString("ERR_FormsAuthNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user impersonation error has occurred..
        /// </summary>
        internal static string ERR_Impersonation {
            get {
                return ResourceManager.GetString("ERR_Impersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} instance cannot be null..
        /// </summary>
        internal static string ERR_InstanceNotNull {
            get {
                return ResourceManager.GetString("ERR_InstanceNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response ID received from input..
        /// </summary>
        internal static string ERR_InvalidResponseId {
            get {
                return ResourceManager.GetString("ERR_InvalidResponseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} location cannot be null..
        /// </summary>
        internal static string ERR_LocationNotNull {
            get {
                return ResourceManager.GetString("ERR_LocationNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max cannot be less than zero..
        /// </summary>
        internal static string ERR_MaxNotLessThanZero {
            get {
                return ResourceManager.GetString("ERR_MaxNotLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min cannot be greater than max..
        /// </summary>
        internal static string ERR_MinNotGreaterThanMax {
            get {
                return ResourceManager.GetString("ERR_MinNotGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding the specified property name. Ensure the specified property name [{0}] is a member of the current object..
        /// </summary>
        internal static string ERR_MissingPropertyName {
            get {
                return ResourceManager.GetString("ERR_MissingPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be of type.
        /// </summary>
        internal static string ERR_MustBeType {
            get {
                return ResourceManager.GetString("ERR_MustBeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key columns found. A minimum of 1 key is required..
        /// </summary>
        internal static string ERR_NoKeyColumnsFound {
            get {
                return ResourceManager.GetString("ERR_NoKeyColumnsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be non-negative value..
        /// </summary>
        internal static string ERR_NonNegativeValue {
            get {
                return ResourceManager.GetString("ERR_NonNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string ERR_NonNegativeValueAndLessSize {
            get {
                return ResourceManager.GetString("ERR_NonNegativeValueAndLessSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No properties were found to build query..
        /// </summary>
        internal static string ERR_NoPropertiesFound {
            get {
                return ResourceManager.GetString("ERR_NoPropertiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be greater than random buffer..
        /// </summary>
        internal static string ERR_NotGreaterThanBuffer {
            get {
                return ResourceManager.GetString("ERR_NotGreaterThanBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null or empty..
        /// </summary>
        internal static string ERR_NullOrEmpty {
            get {
                return ResourceManager.GetString("ERR_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type {0}..
        /// </summary>
        internal static string ERR_ObjectMustBeOfType {
            get {
                return ResourceManager.GetString("ERR_ObjectMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} object cannot be null..
        /// </summary>
        internal static string ERR_ObjectNotNull {
            get {
                return ResourceManager.GetString("ERR_ObjectNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpContext.Current page handler cannot be null..
        /// </summary>
        internal static string ERR_PageHandlerNull {
            get {
                return ResourceManager.GetString("ERR_PageHandlerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path provided could not be resolved..
        /// </summary>
        internal static string ERR_PathNotResolved {
            get {
                return ResourceManager.GetString("ERR_PathNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} provider cannot be null..
        /// </summary>
        internal static string ERR_ProviderNotNull {
            get {
                return ResourceManager.GetString("ERR_ProviderNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redis connection string cannot be empty. See documentation on how to set the connection string..
        /// </summary>
        internal static string ERR_RedisConnectionNotNullOrEmpty {
            get {
                return ResourceManager.GetString("ERR_RedisConnectionNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid serializer configuration. Either both the serializer and deserializer must be set or both must be null..
        /// </summary>
        internal static string ERR_RedisInvalidSerializerConfiguration {
            get {
                return ResourceManager.GetString("ERR_RedisInvalidSerializerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key cannot be null..
        /// </summary>
        internal static string ERR_RegistryKeyNull {
            get {
                return ResourceManager.GetString("ERR_RegistryKeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred serializing {0}. See inner exception for more details..
        /// </summary>
        internal static string ERR_SerializingInnerEx {
            get {
                return ResourceManager.GetString("ERR_SerializingInnerEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        internal static string ERR_StreamNotReadable {
            get {
                return ResourceManager.GetString("ERR_StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        internal static string ERR_StreamNotWritable {
            get {
                return ResourceManager.GetString("ERR_StreamNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to be converted must be in the following format: [HH],[MM],[SS]..
        /// </summary>
        internal static string ERR_StringTimeSpanFormat {
            get {
                return ResourceManager.GetString("ERR_StringTimeSpanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be serializable..
        /// </summary>
        internal static string ERR_TypeNotSerializable {
            get {
                return ResourceManager.GetString("ERR_TypeNotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;null&apos; was found where an instance of IEmailMessage was expected..
        /// </summary>
        internal static string ERR_ValueNullAndNotIEmailMessage {
            get {
                return ResourceManager.GetString("ERR_ValueNullAndNotIEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value is out of range..
        /// </summary>
        internal static string ERR_ValueOutOfRange {
            get {
                return ResourceManager.GetString("ERR_ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web request response stream cannot be null..
        /// </summary>
        internal static string ERR_WebReqResponseNull {
            get {
                return ResourceManager.GetString("ERR_WebReqResponseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web request response cannot be null..
        /// </summary>
        internal static string ERR_WebResponeNull {
            get {
                return ResourceManager.GetString("ERR_WebResponeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error occurred. Additional information: &apos;{0}&apos;..
        /// </summary>
        internal static string InternalExceptionMessage {
            get {
                return ResourceManager.GetString("InternalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing a service notification message box with a Help button is not a valid operation..
        /// </summary>
        internal static string MessageBoxTimeoutHelpButtonEx {
            get {
                return ResourceManager.GetString("MessageBoxTimeoutHelpButtonEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application..
        /// </summary>
        internal static string MessageBoxTimeoutNoUserInteractiveEx {
            get {
                return ResourceManager.GetString("MessageBoxTimeoutNoUserInteractiveEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing a service notification message box with an owner window is not a valid operation. Use the Show method that does not take an owner..
        /// </summary>
        internal static string MessageBoxTimeoutNoWindowOwner {
            get {
                return ResourceManager.GetString("MessageBoxTimeoutNoWindowOwner", resourceCulture);
            }
        }
    }
}
